name: Publish Branch

on:
    workflow_call:

jobs:
    release_candidate:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: write
        env:
            BRANCH_NAME: next
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '24.x'
                  registry-url: 'https://registry.npmjs.org'
                  cache: 'npm'

            # Trusted publishing requires npm >= 11.5.1
            - run: npm install -g npm@latest

            - run: npm ci
            - run: npm run build:lib

            - name: Get current package.json version
              run: echo "PACKAGE_VERSION=$(npm pkg get version | tr -d '"')" >> $GITHUB_ENV

            # get the sort SHA and add it into the environment variables
            - name: Setup Branch Release Candidate Version
              run: echo "BRANCH_VERSION=$PACKAGE_VERSION-$BRANCH_NAME.${GITHUB_SHA::7}" >> $GITHUB_ENV

            - name: Bump version
              run: npm version $BRANCH_VERSION --no-git-tag-version --force

            - name: Publish a new branch release candidate version
              run: npm publish --tag $BRANCH_NAME
